yanshee:
# Publish all joint states---------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position controllers-----------------------------------
  head_position_controller:
    type: position_controllers/JointPositionController
    joint: head_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}


  left_arm1_controller:
    type: position_controllers/JointPositionController
    joint: left_arm1_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  left_arm2_controller:
    type: position_controllers/JointPositionController
    joint: left_arm2_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  left_arm3_controller:
    type: position_controllers/JointPositionController
    joint: left_arm3_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  right_arm1_controller:
    type: position_controllers/JointPositionController
    joint: right_arm1_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  right_arm2_controller:
    type: position_controllers/JointPositionController
    joint: right_arm2_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  right_arm3_controller:
    type: position_controllers/JointPositionController
    joint: right_arm3_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}


  left_leg1_controller:
    type: position_controllers/JointPositionController
    joint: left_leg1_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  left_leg2_controller:
    type: position_controllers/JointPositionController
    joint: left_leg2_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}


  left_leg3_controller:
    type: position_controllers/JointPositionController
    joint: left_leg3_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  left_leg4_controller:
    type: position_controllers/JointPositionController
    joint: left_leg4_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  left_leg5_controller:
    type: position_controllers/JointPositionController
    joint: left_leg5_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}


  right_leg1_controller:
    type: position_controllers/JointPositionController
    joint: right_leg1_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  right_leg2_controller:
    type: position_controllers/JointPositionController
    joint: right_leg2_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  right_leg3_controller:
    type: position_controllers/JointPositionController
    joint: right_leg3_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  right_leg4_controller:
    type: position_controllers/JointPositionController
    joint: right_leg4_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}

  right_leg5_controller:
    type: position_controllers/JointPositionController
    joint: right_leg5_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}


/gazebo_ros_control:
  pid_gains:
    head_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_arm1_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_arm2_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_arm3_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_arm1_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_arm2_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_arm3_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_leg1_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_leg2_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_leg3_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_leg4_joint:
      p: 1
      i: 0.01
      d: 10.0

    left_leg5_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_leg1_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_leg2_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_leg3_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_leg4_joint:
      p: 1
      i: 0.01
      d: 10.0

    right_leg5_joint:
      p: 1
      i: 0.01
      d: 10.0
